repos:
  - repo: https://github.com/cvanloo/no-checkin
    rev: v0.1.0
    hooks:
      - id: nocheckin
  - repo: https://github.com/awslabs/git-secrets
    rev: 1.3.0
    hooks:
      - id: git-secrets
