repos:
  - repo: https://github.com/cvanloo/no-checkin
    rev: v0.1.1
    hooks:
      - id: nocheckin
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
